name: Test Code

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: test_code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Linting
        run: npm run lint

      - name: Security audit
        run: npm run npmAudit

      - name: Build files
        run: npm run build

       - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
